### ISSUE TITLE
Plugin does not show up in OBS

### ISSUE THREAD

**Issue by Algram** [CatxFish/obs-v4l2sink#24]
Hi there,

after installing the plugin exactly like described in your README.md, the menu entry does not show up in obs-studio.

I am using Fedora 31.

![image](https://user-images.githubusercontent.com/5053729/77645612-e6e92400-6f5a-11ea-8f78-4771df78ad6d.png)

The plugin shows never up in the loaded section here. I tried several different locations for the `.so`-plugin file, but I can't get it to be recognized.

Has anyone else the same problem?

Thanks!

**Comment by codycraven** [comment]
Currently having the same issue under Ubuntu 19.10 (first attempt using obs-v4l2sink).

**Comment by codycraven** [comment]
My solution was found in: https://github.com/CatxFish/obs-v4l2sink/issues/17#issuecomment-603125325

```
mkdir -p ~/.config/obs-studio/plugins/v4l2sink/bin/64bit
cp /usr/lib/obs-plugins/v4l2sink.so ~/.config/obs-studio/plugins/v4l2sink/bin/64bit
```

**Comment by codycraven** [comment]
Further update, turns out it's related to the OBS version. I updated to the latest OBS (instead of what `apt` was giving me) and I ended up with two v4l2sink plugins in the tools menu.

I removed the one I copied to `~/.config/obs-studio/plugins/v4l2sink/` and now it works exactly as the instructions guided.

**Comment by Algram** [comment]
Thanks for your input! I was able to solve this for Fedora specifically. For anyone else having problems: You need to copy the plugin file to `/usr/share/obs/obs-plugins/v4l2sink` this is the only thing that worked for me on Fedora.
