### ISSUE TITLE
Won't show up, I am using the flatpak version of OBS

### ISSUE THREAD

**Issue by IAmV0id** [CatxFish/obs-v4l2sink#64]
Tried the solutions given in other issues but it didn't work.

**Comment by IAmV0id** [comment]
I'm using Pop!_OS 20.04

**Comment by flavorjones** [comment]
Please see https://github.com/flathub/com.obsproject.Studio/issues/65

**Comment by IAmV0id** [comment]
Thank you so much, it worked! I feel like this should be in the read me.
