### ISSUE TITLE
obs-v4l2sink not showing option in obs -> tools

### ISSUE THREAD

**Issue by lalitkashyapkumar** [CatxFish/obs-v4l2sink#66]
I have installed obs-v4l2sink Debian package in my Kali Linux 2020.1 but the option of starting camera is not showing in tools of OBS studio 25.0.8+dfsg1-3

**Comment by manuelsoldini** [comment]
hey @lalitkashyapkumar  how did you fix this?

**Comment by manuelsoldini** [comment]
nevermind I just did:
ln -s /usr/lib/obs-plugins/v4l2sink.so /usr/lib/x86_64-linux-gnu/obs-plugins/v4l2sink.so
