### ISSUE TITLE
No Tools > V4L2 Video Output

### ISSUE THREAD

**Issue by fsikora** [CatxFish/obs-v4l2sink#77]
Hi,
I followed the instructions, the cmake / make install made no errors.
I do have v4l2sink.so in /usr/lib/obs-plugins.
I do have a virtual cam in /dev
But no  V4L2 Video Output in my Tools menu. 
Linux Mint 20 here.

**Comment by fsikora** [comment]
You need to move the .so from /usr/lib/obs-plugins to /usr/lib/x86_64-linux-gnu/obs-plugins

**Comment by joe-mojo** [comment]
Hi, this is the opposite for me. 
I had de the same issue.
All other OBS plugins are in `/usr/lib/obs-plugins`, so I had to move the .so from `/usr/lib/x86_64-linux-gnu/obs-plugins` to `/usr/lib/obs-plugins`. Then if worked flawlessly.
(I'm on Ubuntu 20.04.1)
