### ISSUE TITLE
missing LIBOBS_LIB

### ISSUE THREAD

**Issue by DorKeinath** [CatxFish/obs-v4l2sink#79]
With

`cmake -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" -DCMAKE_INSTALL_PREFIX=/usr ..
`

I get

-- Could NOT find Libobs (missing: LIBOBS_LIB) 
CMake Error at external/FindLibObs.cmake:106 (message):
  Could not find the libobs library
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)

-- Configuring incomplete, errors occurred!

What can I do? qtbase5-dev is uptodate.

**Comment by kevinkk525** [comment]
Same problem here

**Comment by clemensvonmolo** [comment]
Try doing 
``` sudo apt install libobs-dev ```
I had the same error and this fixed it for me.

**Comment by minced1** [comment]
> Try doing
> `sudo apt install libobs-dev`
> I had the same error and this fixed it for me.

Is there a solution for Fedora? I tried to install it using dnf but it's not in the repositories. I installed RPMFusion both the free and the non-free one.

**Comment by kevinkk525** [comment]
> sudo apt install libobs-dev

Thanks that worked! Didn't think about that.

**Comment by Cimbali** [comment]
Checkout the PR #92 which should fix this issue

**Comment by manuGe** [comment]
> > Try doing
> > `sudo apt install libobs-dev`
> > I had the same error and this fixed it for me.
> 
> Is there a solution for Fedora? I tried to install it using dnf but it's not in the repositories. I installed RPMFusion both the free and the non-free one.

@JaCaGu477 after I installed the package `obs-studio-devel` from rpmfusion-free, I was able to build it.

**Comment by DorKeinath** [comment]
Thank you. There is no error anymore.
