### ISSUE TITLE
Video is flipped

### ISSUE THREAD

**Issue by ahmadnassri** [CatxFish/obs-v4l2sink#9]
everything works, except the video seems to be flipped upside down!

steps to re-produce:

```
sudo apt-get install v4l2loopback-utils
```

then in OBS:

![image](https://user-images.githubusercontent.com/183195/50927636-59d5b000-1426-11e9-9db7-5dc554b6aee7.png)

output of `v4l2-ctl -d /dev/video4 -l`:

```
User Controls

                    keep_format 0x0098f900 (bool)   : default=0 value=0
              sustain_framerate 0x0098f901 (bool)   : default=0 value=0
                        timeout 0x0098f902 (int)    : min=0 max=100000 step=1 default=0 value=0
               timeout_image_io 0x0098f903 (bool)   : default=0 value=0
```

what information can I provide to assist in debugging?

**Comment by CatxFish** [comment]
Upside down? not horizontal flip? What is the video setting on OBS you are using?

**Comment by ahmadnassri** [comment]
I should have taken a picture of the vertical flip, because now the problem is gone ... so, trying it again today to get more details, it's now a horizontal flip!! 

I should also clarify this happens in browser applications, I use `guvcview` for editing web cam settings, and that seems to display the correct orientation / direction.

not sure what the issue was in my first attempt _(i had trouble re-activating `v4l2loopback` device the second time around)_

**Comment by ahmadnassri** [comment]
also tried with `camorama` and it seems fine, so maybe this is browser related?

**Comment by CatxFish** [comment]
Horizontal flip is usually cause by 3rd party software,  especially on video chat platform
They want to make people see the image in the same direction , but if that bothers you , you can use obs built-in filter to flip image before sending to another software.

**Comment by ahmadnassri** [comment]
@CatxFish thank you, yes it seems to be the case, I've been searching for filters (for whole scene) that can do that, are you aware of any? built-in ones don't seem to do that.

**Comment by CatxFish** [comment]
It's my fault. Not an built-in filter , the flip horizontal option is in source->right click->transform menu.

**Comment by ahmadnassri** [comment]
ah, right. yeah, I'm using those for now. was hoping for a whole scene flip .. but doesn't seem like that's possible.

Thank you for all your help and responses.

**Comment by ubitux** [comment]
> ah, right. yeah, I'm using those for now. was hoping for a whole scene flip .. but doesn't seem like that's possible.

Just for the record, as I came across this issue while trying to solve that: you can actually flip the whole scene by creating a new scene, and using your original composed scene as source. Then you can apply any transformation on that source.

I also realized that the mirroring effects visio services uses only applies to you (at least in my experience), so flipping was actually not needed in my case.

**Comment by EvanCarroll** [comment]
> mirroring effects visio services uses only applies to you

Yes, that's the takeaway perhaps it's better to say they're flipping the image only on **playback** not on transmission, and only if it's your transmission.
