### ISSUE TITLE
cp: cannot stat '/usr/lib/obs-plugins/v4l2sink.so': No such file or directory

### ISSUE THREAD

**Issue by ghost** [CatxFish/obs-v4l2sink#97]
I dont see the tool in obs so i try this:
 cp /usr/lib/obs-plugins/v4l2sink.so /usr/lib/x86_64-linux-gnu/obs-plugins/
And this is the output:
cp: cannot stat '/usr/lib/obs-plugins/v4l2sink.so': No such file or directory
Anyone know what to do?

**Comment by ispanos** [comment]
Try this:
```
mkdir -p ~/.config/obs-studio/plugins/v4l2sink/bin/64bit/
ln -s /usr/lib/obs-plugins/v4l2sink.so ~/.config/obs-studio/plugins/v4l2sink/bin/64bit/
```

**Comment by ghost** [comment]
i tried but it still gives me this error:
cp: cannot stat '/usr/lib/obs-plugins/v4l2sink.so': No such file or directory
(when i try this:cp /usr/lib/obs-plugins/v4l2sink.so /usr/lib/x86_64-linux-gnu/obs-plugins/)

**Comment by ispanos** [comment]
Did you use `mv` at somepoint maybe?
How did you install the plugin?

**Comment by ghost** [comment]
using the method in github
would there be a way to reset it to its original position?

**Comment by ispanos** [comment]
> using the method in github

Did you build it from source? If you are on ubuntu you could use the `.deb` package found in the release page.

> would there be a way to reset it to its original position?

Yes. If you knew where you moved it to. But the `cp` command you are using wouldn't work even if the file was there. install the deb package and then do as i described in my first comment.

**Comment by ghost** [comment]
im on mint and can i use grep to find it if yes how?

**Comment by ispanos** [comment]
Mint works too. its based on ubuntu. do as I said if you try installing it again.

`sudo find / -type f -name "*v4l2sink*"` Maybe!?

**Comment by ghost** [comment]
~$ sudo find / -type f -name "*v4l2sink*"
[sudo] password for oem:                   
/usr/lib/x86_64-linux-gnu/obs-plugins/v4l2sink.so
find: ‘/run/user/29999/gvfs’: Permission denied
/home/oem/obs-v4l2sink/build/CMakeFiles/v4l2sink.dir/src/v4l2sink.cpp.o
/home/oem/obs-v4l2sink/build/CMakeFiles/v4l2sink.dir/src/v4l2sinkproperties.cpp.o
/home/oem/obs-v4l2sink/build/v4l2sink.so
/home/oem/obs-v4l2sink/build/v4l2sink_autogen/UVLADIE3JM/moc_v4l2sinkproperties.cpp
/home/oem/obs-v4l2sink/build/v4l2sink_autogen/include/ui_v4l2sinkproperties.h
/home/oem/obs-v4l2sink/src/v4l2sink.h
/home/oem/obs-v4l2sink/src/v4l2sinkproperties.cpp
/home/oem/obs-v4l2sink/src/v4l2sinkproperties.h
/home/oem/obs-v4l2sink/src/v4l2sinkproperties.ui
/home/oem/obs-v4l2sink/src/v4l2sink.cpp
/home/oem/.local/share/Trash/files/obs-v4l2sink/src/v4l2sink.h
/home/oem/.local/share/Trash/files/obs-v4l2sink/src/v4l2sinkproperties.cpp
/home/oem/.local/share/Trash/files/obs-v4l2sink/src/v4l2sinkproperties.h
/home/oem/.local/share/Trash/files/obs-v4l2sink/src/v4l2sinkproperties.ui
/home/oem/.local/share/Trash/files/obs-v4l2sink/src/v4l2sink.cpp
/home/oem/.local/share/Trash/info/obs-v4l2sink.trashinfo

**Comment by ispanos** [comment]
Please install the Deb package iny the release page.

**Comment by ghost** [comment]
wait im actually so stupid:/usr/lib/x86_64-linux-gnu/obs-plugins/v4l2sink.so

**Comment by ghost** [comment]
i already copyed it thats why it dosent work

**Comment by ispanos** [comment]
You mean you moved it.

**Comment by ghost** [comment]
probably

**Comment by ghost** [comment]
but i still dont see it in obs

**Comment by ispanos** [comment]
> but i still dont see it in obs

you did this :
```
mkdir -p ~/.config/obs-studio/plugins/v4l2sink/bin/64bit/
ln -s /usr/lib/obs-plugins/v4l2sink.so ~/.config/obs-studio/plugins/v4l2sink/bin/64bit/
```

And it still doesn't show up?

**Comment by ghost** [comment]
yes but i am reinstalling from scratch

**Comment by ispanos** [comment]
Have you installed `v4l-utils v4l2loopback-dkms v4l2loopback-utils`?
And ran
`sudo modprobe v4l2loopback devices=1 card_label="OBS Cam" exclusive_caps=1` ?

**Comment by ochen1** [comment]
> Have you installed `v4l-utils v4l2loopback-dkms v4l2loopback-utils`?
> And ran
> `sudo modprobe v4l2loopback devices=1 card_label="OBS Cam" exclusive_caps=1` ?

That does not affect v4l2sink showing in the toolbar.

And since the OP closed the issue, I would assume they solved it.
